name: Env Variables Demo1

on: workflow_dispatch

env:
  GLOBAL_ENV: "global-value"

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: production  

    steps:
      - name: Use environment variables
        env:
          API_URL: ${{ vars.API_URL }}
          APP_MODE: ${{ vars.APP_MODE }}
          DB_PASS: ${{ secrets.DB_PASSWORD}}
        run: |
          echo "API URL: $API_URL"
          echo "App Mode: $APP_MODE"
          echo "DB PASS: $DB_PASS"